const assert=require('assert');
global.window={};
const {score}=require('../js/ats.js');
require('../js/data.js');
const D=window.RF_DATA;
assert(D&&D.sample,'RF_DATA.sample must exist');
const good=score(D.sample);
assert(good.total>=90&&good.total<=100,'good sample should score high, got '+good.total);
assert.strictEqual(good.checks.length,8,'engine must run 8 checks');
assert.strictEqual(good.checks.reduce(function(s,c){return s+c.max;},0),100,'weights must sum to 100');
const bad=score({});
assert.strictEqual(bad.total,0,'empty resume must score 0');
const mid=score({email:'a@b.co',phone:'1234567',skills:['a','b','c','d','e','f']});
assert.strictEqual(mid.total,25,'partial resume expected 25, got '+mid.total);
assert.strictEqual(D.templates.length,9,'must ship 9 templates');
assert(D.pricing.some(function(p){return p.popular;}),'one plan must be popular');
assert(D.features.length===6&&D.faq.length===5&&D.testimonials.length===4,'landing data complete');
const cover=require('../js/coverlib.js');
['confident','friendly','formal'].forEach(function(t){
const g=cover.generate(t,{company:'Acme',role:'PM',name:'Sam'});
assert(g.hook&&g.body&&g.close,'cover parts must exist for '+t);
assert(g.hook.indexOf('Acme')!==-1||g.body.indexOf('Acme')!==-1,'company must be mentioned for '+t);
});
assert(cover.generate('unknown',{}).hook.length>0,'unknown tone falls back to confident');
const jdm=require('../js/match.js');
const jd='We are hiring a Product Designer with Figma, prototyping, design systems and user research experience. Strong Figma skills required.';
const m=jdm.match(jd,D.sample);
assert(m.keywords.length>0,'keywords must be extracted');
assert(m.matched.indexOf('figma')!==-1,'figma should match the sample resume');
assert(m.pct>=30,'sample should cover a good chunk of the JD, got '+m.pct);
assert.strictEqual(jdm.match(jd,{}).pct,0,'empty resume matches nothing');
assert.strictEqual(jdm.match('',D.sample).pct,0,'empty JD yields 0');
const EX=require('../js/examples.js');
assert.strictEqual(Object.keys(EX).length,5,'must ship 5 examples');
Object.keys(EX).forEach(function(id){
const e=EX[id];
assert(e.label&&e.blurb&&e.resume,'example '+id+' must have label, blurb, resume');
const s=score(e.resume);
assert(s.total>=90,'example '+id+' must score 90+, got '+s.total);
});
const Q=require('../js/questions.js');
assert.strictEqual(Object.keys(Q).length,6,'must ship 6 question tracks');
Object.keys(Q).forEach(function(r){
assert(Q[r].length>=8,'track '+r+' must have 8+ questions');
Q[r].forEach(function(it){assert(it.q&&it.tip,'every question in '+r+' needs q and tip');});
});
const BL=require('../js/bulletlib.js');
const goodB=BL.analyze('Led redesign of the checkout flow, increasing conversion 32% across 1.2M users');
assert.strictEqual(goodB.score,100,'strong bullet should score 100, got '+goodB.score);
const badB=BL.analyze('responsible for stuff');
assert(badB.score<=25,'weak bullet should score low, got '+badB.score);
assert.strictEqual(goodB.checks.length,4,'bullet doctor runs 4 checks');
D.sample.experience.forEach(function(e){e.bullets.forEach(function(b){
assert.strictEqual(BL.analyze(b).score,100,'sample bullet should pass doctor: '+b);
});});
const P=require('../js/parse.js');
const goodTxt=['Alex Morgan','alex.morgan@email.com  +1 (415) 555-0134','Summary','Product designer with impact.','Experience','- Led redesign increasing conversion 32%','- Built design system adopted by 6 teams','- Reduced onboarding time 40%','- Shipped mobile app rated 4.8 stars','- Managed research with 40 users','Education','B.Des, CCA, 2019','Skills','Figma, Prototyping, Research'].join('\n');
const pr=P.analyzeText(goodTxt);
assert(pr.total>=85,'parsed resume should score high, got '+pr.total);
assert.strictEqual(pr.checks.length,10,'text scanner runs 10 checks');
assert.strictEqual(pr.checks.reduce(function(s,c){return s+c.max;},0),100,'text weights sum to 100');
assert(P.analyzeText('').total<=10,'empty text scores near zero');
assert(pr.stats.bullets===5&&pr.stats.words>10,'stats computed');
console.log('ALL TESTS PASSED');
