const assert=require('assert');
global.window={};
const {score}=require('../js/ats.js');
require('../js/data.js');
const D=window.RF_DATA;
assert(D&&D.sample,'RF_DATA.sample must exist');
const good=score(D.sample);
assert(good.total>=90&&good.total<=100,'good sample should score high, got '+good.total);
assert.strictEqual(good.checks.length,8,'engine must run 8 checks');
assert.strictEqual(good.checks.reduce(function(s,c){return s+c.max;},0),100,'weights must sum to 100');
const bad=score({});
assert.strictEqual(bad.total,0,'empty resume must score 0');
const mid=score({email:'a@b.co',phone:'1234567',skills:['a','b','c','d','e','f']});
assert.strictEqual(mid.total,25,'partial resume expected 25, got '+mid.total);
assert.strictEqual(D.templates.length,6,'must ship 6 templates');
assert(D.pricing.some(function(p){return p.popular;}),'one plan must be popular');
assert(D.features.length===6&&D.faq.length===5&&D.testimonials.length===4,'landing data complete');
const cover=require('../js/coverlib.js');
['confident','friendly','formal'].forEach(function(t){
const g=cover.generate(t,{company:'Acme',role:'PM',name:'Sam'});
assert(g.hook&&g.body&&g.close,'cover parts must exist for '+t);
assert(g.hook.indexOf('Acme')!==-1||g.body.indexOf('Acme')!==-1,'company must be mentioned for '+t);
});
assert(cover.generate('unknown',{}).hook.length>0,'unknown tone falls back to confident');
const jdm=require('../js/match.js');
const jd='We are hiring a Product Designer with Figma, prototyping, design systems and user research experience. Strong Figma skills required.';
const m=jdm.match(jd,D.sample);
assert(m.keywords.length>0,'keywords must be extracted');
assert(m.matched.indexOf('figma')!==-1,'figma should match the sample resume');
assert(m.pct>=30,'sample should cover a good chunk of the JD, got '+m.pct);
assert.strictEqual(jdm.match(jd,{}).pct,0,'empty resume matches nothing');
assert.strictEqual(jdm.match('',D.sample).pct,0,'empty JD yields 0');
console.log('ALL TESTS PASSED');
